name: ondas2
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.7
    - scipy
    - matplotlib
    - netCDF4
    - notebook
    - numpy
    - pandas
    - panel
    - progressbar
    - plotly
    - xarray
    - gsw
    - sympy
    - UTide
    - shapely
    - jupyterlab
    - folium
    - seaborn
    - windrose
    - basemap
    
    
    
